name: LocaleLib
main: me.pikamug.localelib.LocaleLib
version: 4.0.0-Folia
api-version: 1.13
description: Show translated names of items, entities & more in client's language
website: https://github.com/PikaMug/LocaleLib
author: PikaMug
